/* eslint-disable new-cap */
import Navigation from "@/components/Navigation";
import "./globals.css";
import { Lexend } from "next/font/google";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navigation />
      <body className={lexend.className}>{children}</body>
    </html>
  );
}
