/* eslint-disable new-cap */
import "./globals.css";
import { Lexend } from "next/font/google";

const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} bg-projects-black flex flex-col items-center justify-center min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
